# This is a basic workflow to help you get started with Actions

name: Deploy notebook to databrick

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v
        with:
          python-version: '3.8'

      - name: Install Databrick CLI
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli

      - name: configure databrick cli
        run: |
          export DATABRICKS_HOST=${{secrets.DATABRICKS_HOST}}
          export DATABRICKS_TOKEN=${{secrets.DATABRICKS_TOKEN}}

