# This is a basic workflow to help you get started with Actions

name: Deploy notebook to databrick

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Databrick CLI
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli
          databricks -v

      - name: Configure databrick cli
        run: |
          databricks auth login --host https://accounts.cloud.databricks.com/workspaces/3183095243678594?account_id=c164a2e9-fd83-4655-a6c3-a75e409ef4af --client-id a55ba7f6-67fb-4cc5-9a87-83290e5aba0d --client-secrets dose679f01736e2ece7e487c54871f7e97f0

      - name: deploy code to databrick workspace
        run: |
          databricks workspace import_dir ./ /workspace

      # - name: Create Databricks Job
      #   run: |
      #     databricks jobs create --json-file job_definition.json

      # - name: Run Databricks Job
      #   run: |
      #     databricks jobs run-now --job-id JOB_ID

