# This is a basic workflow to help you get started with Actions

name: Deploy notebook to databrick

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # - name: Install Databrick CLI
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install databricks-cli
      #     databricks -v

      # - name: Configure databrick cli
      #   run: |
      #     export DATABRICKS_HOST=https://dbc-86c504bb-e56a.cloud.databricks.com
      #     export DATABRICKS_CLIENT_ID=a55ba7f6-67fb-4cc5-9a87-83290e5aba0d
      #     export DATABRICKS_CLIENT_SECRET=dose679f01736e2ece7e487c54871f7e97f0
      #     export account_id=c164a2e9-fd83-4655-a6c3-a75e409ef4af
      #     echo $DATABRICKS_HOST

      - name: Install Databrick CLI
        run: |
          export DATABRICKS_HOST=https://dbc-86c504bb-e56a.cloud.databricks.com/?autoLogin=true&account_id=c164a2e9-fd83-4655-a6c3-a75e409ef4af&o=3183095243678594
          export DATABRICKS_CLIENT_ID=a55ba7f6-67fb-4cc5-9a87-83290e5aba0d
          export DATABRICKS_CLIENT_SECRET=dose679f01736e2ece7e487c54871f7e97f0
          export account_id=c164a2e9-fd83-4655-a6c3-a75e409ef4af        
          echo $DATABRICKS_HOST
          echo $DATABRICKS_CLIENT_ID
          echo $DATABRICKS_CLIENT_SECRET
          echo $account_id
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo >> /home/runner/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt-get install build-essential
          brew install gcc
          brew -v
          brew tap databricks/tap
          brew install databricks
          databricks -v
          databricks workspace list
      # - name: Configure databrick cli
      #   env:
      #     DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
      #     DATABRICKS_CLIENT_ID: ${{secrets.DATABRICKS_CLIENT_ID}}
      #     DATABRICKS_CLIENT_SECRET: ${{secrets.DATABRICKS_CLIENT_SECRET}}
      #   run: |
      #     export DATABRICKS_HOST=$"{secrets.DATABRICKS_HOST}"
      #     export DATABRICKS_CLIENT_ID=$"{secrets.DATABRICKS_CLIENT_ID}"
      #     export DATABRICKS_CLIENT_SECRET=$"{secrets.DATABRICKS_CLIENT_SECRET}"

      # - name: deploy code to databrick workspace
      #   run: |
      #     databricks auth login --host $DATABRICKS_HOST --client-id $DATABRICKS_CLIENT_ID --client-secret DATABRICKS_CLIENT_SECRET

      # - name: Create Databricks Job
      #   run: |
      #     databricks jobs create --json-file job_definition.json

      # - name: Run Databricks Job
      #   run: |
      #     databricks jobs run-now --job-id JOB_ID

